## 3-4 分析の準備

In [1]:
import numpy as np
import pandas as pd

## 3-5 度数分布

In [2]:
category_data = pd.read_csv('3-3-1-fish-species.csv')
print(category_data)

  species
0       A
1       A
2       A
3       B
4       B
5       B
6       B
7       B
8       B
9       B


In [3]:
category_data.species.value_counts(sort=False) # value_counts はpandasシリーズの関数

species
A    3
B    7
Name: count, dtype: int64

In [4]:
numeric_data = pd.read_csv('3-3-2-fish-length.csv')
print(numeric_data)

   length
0    1.91
1    1.21
2    2.28
3    1.01
4    1.00
5    4.50
6    1.96
7    0.72
8    3.67
9    2.55


In [5]:
numeric_data.length.value_counts()

length
1.91    1
1.21    1
2.28    1
1.01    1
1.00    1
4.50    1
1.96    1
0.72    1
3.67    1
2.55    1
Name: count, dtype: int64

In [6]:
numeric_data.length.value_counts(bins=3)

(0.715, 1.98]    6
(1.98, 3.24]     2
(3.24, 4.5]      2
Name: count, dtype: int64

In [7]:
np.arange(0, 6, 1) # 0~5までの等差級数

array([0, 1, 2, 3, 4, 5])

In [9]:
freq = numeric_data.length.value_counts( #freq: 度数分布
    bins=np.arange(0, 6, 1), sort=False)
freq

(-0.001, 1.0]    2
(1.0, 2.0]       4
(2.0, 3.0]       2
(3.0, 4.0]       1
(4.0, 5.0]       1
Name: count, dtype: int64

In [10]:
np.histogram(numeric_data.length, bins=3)

(array([6, 2, 2]), array([0.72, 1.98, 3.24, 4.5 ]))

In [11]:
np.histogram(numeric_data.length, bins=np.arange(0, 6, 1))

(array([1, 5, 2, 1, 1]), array([0, 1, 2, 3, 4, 5]))